import { Recipe } from "../types/recipe.type";

export const seedRecipes: Recipe[] = [
  {
    id: "1",
    name: "Prawn fried rice",
    description: "Delicious prawn fried rice with fresh vegetables",
    // image: "/assets/praw fried rice.webp",
    duration: "10 Mins",
    servings: 2,
    difficulty: "Easy",
    price: 3200,
    ingredients: ["rice", "oil", "curry", "prawns"],
    numberOfIngredients: 4,
    displayMedia: {
      url: "",
      publicId: "",
      type: "image",
    },
  },
  {
    id: "2",
    name: "Turkey fried rice",
    description: "Savory turkey fried rice perfect for any occasion",
    // image: "/assets/realturkeyfriedrice.webp",
    duration: "25 Mins",
    servings: 2,
    difficulty: "Medium",
    price: 3200,
    ingredients: ["rice", "oil", "curry", "prawns"],
    numberOfIngredients: 4,
    displayMedia: {
      url: "",
      publicId: "",
      type: "image",
    },
  },
  {
    id: "3",
    name: "Shrimp and plaintain pottage",
    description: "A unique blend of shrimp and plantain in a delicious pottage",
    // image: "/assets/shrimpand plantain porridge.webp",
    duration: "10 Mins",
    ingredients: ["rice", "oil", "curry", "prawns"],
    servings: 2,
    difficulty: "Easy",
    price: 3200,
    numberOfIngredients: 4,
    displayMedia: {
      url: "",
      publicId: "",
      type: "image",
    },
  },
  {
    id: "4",
    name: "Gizdodo",
    description: "Traditional Gizdodo with a modern twist",
    // image: "/assets/gizdodo.webp",
    duration: "25 Mins",
    servings: 2,
    difficulty: "Medium",
    price: 3200,
    ingredients: ["rice", "oil", "curry", "prawns"],
    numberOfIngredients: 4,
    displayMedia: {
      url: "",
      publicId: "",
      type: "image",
    },
  },
];
